[goldmark.renderer]
	unsafe = true

[goldmark.extensions]
	# definitionList = true
	# footnote = true
	# linkify = true
	# strikethrough = true
	# table = true
	# taskList = true
	typographer = true

[tableOfContents]
	ordered = true

[highlight]
	noClasses = false
