#################
# Site Nav Menu #
#################

[[sitenav]]
	name = "projects"
	URL = "/projects/"
	weight = 1

[[sitenav]]
	name = "articles"
	URL = "/articles/"
	weight = 2

[[sitenav]]
	name = "about"
	URL = "/about/"
	weight = 3

#####################
# Social Media Menu #
#####################

[[social]]
	weight = 1
	identifier = 'twitter'
	name = 'Twitter'
	URL = 'https://twitter.com/MichaelZalla/likes'

[[social]]
	weight = 2
	identifier = 'github'
	name = 'GitHub'
	URL = 'https://github.com/MichaelZalla'

[[social]]
	weight = 3
	identifier = 'linkedin'
	name = 'LinkedIn'
	URL = 'https://linkedin.com/in/michaelzalla'

[[social]]
	weight = 4
	identifier = 'stackoverflow'
	name = 'StackOverflow'
	URL = 'https://stackoverflow.com/users/1623811/michael-zalla?tab=answers&sort=newest'

# [[social]]
# 	weight = 5
# 	identifier = 'pinterest'
# 	name = 'Pinterest'
# 	URL = 'http://www.pinterest.com/michaelzalla/'

[[social]]
	weight = 6
	identifier = 'instagram'
	name = 'Instagram'
	URL = 'https://www.instagram.com/playforsweeps/'
