# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Stroodle"
license = "MIT"
licenselink = "https://github.com/MichaelZalla/zalla-io-website/blob/master/themes/stroodle/LICENSE.md"
description = ""
homepage = "https://github.com/MichaelZalla/zalla-io-website/"
tags = []
features = []
min_version = "0.38.2"

[author]
  name = "Michael Zalla"
  homepage = "https://zalla.io"

[taxonomies]
  tag = "tags"
  project = "projects"
